### PR TITLE
Let EditorialStatus written into CSV by adding the fieldToCsv function in BulkMapping in BulkAd

### PR DESCRIPTION
**Pull request by wenfengzhuo**
When we use BulkFileReader to read a TextAd in csv file which was written by BulkFileWritter, we found that EditorialStatus could not be got, but this status is meaningful for us to use. 

So we create a pull request.

### CODE REVIEW

**Comment by eric-urban** [comment]
Editorial reasons are already provided. I have added an example here: https://github.com/bing-ads-sdk/BingAds-Java-SDK/commit/e92588604a58bdcb0c41261867862afca2a19977

Please let me know if you have any questions.

**Comment by dennis-yemelyanov** [comment]
Thanks! The change makes sense, but currently breaks unit tests. Let's check getEditorialStatus() for null and return null in this case (otherwise .value()).

**Comment by eric-urban** [comment]
I may have misunderstood the original intent of this pull request, so I'll ask you to clarify. If you want the ad editorial status or editorial codes / reasons, they are already available via bulk download. Otherwise are you trying to write editorial status to a file? Its not clear why you want to write a value that is read-only (upload would ignore it), so please clarify the use case - if that is what you are asking for. Thanks!

**Comment by wenfengzhuo** [comment]
Let me explain why we need this.

When we download all objects via bulk download function, you guys gave us a Iterator to get the objects. We don't want to use this objects immediately, instead we are going to store these objects somewhere using your BulkObjectWriter. 

But unfortunately current implementation will not write the EditorialStatus into file, so when I use BulkStreamReader to read the objects, I can't get EditorialStatus.

**Comment by eric-urban** [comment]
OK, understood. The BulkServiceManager class already provides downloadFileAsync. The purpose is as you described i.e. to download the file immediately, and access the contents later. Have you tried this?

// Submit the download request, and the results file will be downloaded to the specified local file. 

File resultFile = BulkService.downloadFileAsync(
		downloadParameters, 
		progress, 
		null).get();

System.out.printf("Download result file: %s\n", resultFile.getName());

// If you are storing the file to be read later, take note of the file types.
// For example if you set LastSyncTimeInUTC to null, the contents of the file 
// represent a full download.

BulkFileReader fullDownloadReader = new BulkFileReader(
		resultFile, 
		ResultFileType.FULL_DOWNLOAD, 
		DownloadFileType.CSV);

for(BulkEntity entity : fullDownloadReader.getEntities()){
	if(entity instanceof BulkTextAd){
		System.out.printf("EditorialStatus: %s\n", ((BulkTextAd) entity).getTextAd().getEditorialStatus());
	}
}


Does this help?

Best regards,
Eric

**Comment by wenfengzhuo** [comment]
The key point for my pull request is not how to correctly read the value from a result file. The point is when I use the writer to write some value into file, I could not get the original value I wrote into that file. The writer and the reader are not compatible and consistent.

**Comment by dennis-yemelyanov** [comment]
Thanks for submitting this pull request. It was [integrated](https://github.com/bing-ads-sdk/BingAds-Java-SDK/commit/189673fb2fcb8e5a8e72b545413f53a06f1f9488#diff-f542a6ea7aece3e4f82f274c5cc186ba) with version 9.3.2.

**Pull request closed without merging**
